### ISSUE TITLE
Order table by data in whiteboard 

### ISSUE THREAD

**Issue by WilsonKathleen** [mozilla/mediawiki-bugzilla#106]
Would you please tell me how to get order (sort) to work in the following table?

```
<bugzilla>
    {
        "component":"Common CA Database",
        "status":["UNCONFIRMED", "NEW", "ASSIGNED", "REOPENED"], 
        "whiteboard":"ccadb-roadmap",
        "cf_blocking_b2g_type":"contains",
        "include_fields": ["id", "summary", "status", "whiteboard", "assigned_to", "last_change_time"],
        "order": "whiteboard"
    }
</bugzilla>
```

**Comment by cpeterso** [comment]
@WilsonKathleen, the problem is that some field have different names in the Bugzilla filters and `include_fields`. I think this is an artifact of the Bugzilla API used by the bug wiki tables (but that doesn't mean it couldn't be made more consistent).

I maintain an unofficial list of the different field names here that I've reversed engineered here:

https://wiki.mozilla.org/User:Cpeterson

For your query, you just need to replace `"order": "whiteboard"` with `"order": "status_whiteboard"` like this:

```
<bugzilla>
    {
        "component":"Common CA Database",
        "status":["UNCONFIRMED", "NEW", "ASSIGNED", "REOPENED"],
        "whiteboard":"ccadb-roadmap",
        "cf_blocking_b2g_type":"contains",
        "include_fields": ["id", "summary", "status", "whiteboard", "assigned_to", "last_change_time"],
        "order": "status_whiteboard"
    }
</bugzilla>
```

Some other simplifications you might consider for your query:

* To only include open bugs, you can replace `"status":["UNCONFIRMED", "NEW", "ASSIGNED", "REOPENED"],` with just `"resolution": "---",`
* Why do you need `"cf_blocking_b2g_type":"contains",`?
* You can replace the cumbersome list of individually-quoted strings `"include_fields": ["id", "summary", "status", "whiteboard", "assigned_to", "last_change_time"],` with one string containing a comma-separated list of field names like `"include_fields": "id, summary, status, whiteboard, assigned_to, last_change_time",`
* Since you are sorting by whiteboard, I would suggest making the whiteboard the leftmost column.

Altogether:

```
<bugzilla>
    {
        "component":"Common CA Database",
        "resolution": "---",
        "status_whiteboard":"ccadb-roadmap",
        "include_fields": "whiteboard, id, summary, status, assigned_to, last_change_time",
        "order": "status_whiteboard"
    }
</bugzilla>
```

**Comment by WilsonKathleen** [comment]
I greatly appreciate your quick response and recommendations. Thanks!
